// ============================================
// DADOS COMPLETOS DA CIAP-2
// Classificação Internacional de Atenção Primária - 2ª Edição
// Fonte: WONCA - Organização Mundial dos Médicos de Família
// Versão oficial adotada pelo e-SUS APS e PEC - Brasil
// ============================================

const CIAP2_DADOS = {
    // Estrutura: 17 capítulos (letras A a Z)
    // Cada capítulo tem 7 componentes padronizados:
    // 1 - Sinais/Sintomas (01-29)
    // 2 - Procedimentos Diagnósticos/Preventivos (30-49)
    // 3 - Medicações/Tratamentos/Procedimentos (50-59)
    // 4 - Resultados de Exames (60-61)
    // 5 - Procedimentos Administrativos (62)
    // 6 - Encaminhamentos/Outras Razões (63-69)
    // 7 - Doenças/Problemas de Saúde (70-99)

    // ===== CAPÍTULO A - GERAL E INESPECÍFICO =====
    A: {
        nome: 'Geral e Inespecífico',
        descricao: 'Problemas gerais, sintomas inespecíficos e condições sistêmicas',
        rubricas: {
            // Componente 1: Sinais e Sintomas (01-29)
            'A01': { nome: 'Dor generalizada/múltipla', componente: 1 },
            'A02': { nome: 'Calafrios', componente: 1 },
            'A03': { nome: 'Febre', componente: 1 },
            'A04': { nome: 'Cansaço/fadiga/astenia', componente: 1 },
            'A05': { nome: 'Sensação de doença/indisposição', componente: 1 },
            'A06': { nome: 'Desmaio/síncope', componente: 1 },
            'A07': { nome: 'Coma', componente: 1 },
            'A08': { nome: 'Inchaço/edema generalizado', componente: 1 },
            'A09': { nome: 'Problemas de sudorese', componente: 1 },
            'A10': { nome: 'Sangramento/hemorragia NE', componente: 1 },
            'A11': { nome: 'Dor torácica NE', componente: 1 },
            'A13': { nome: 'Preocupação/medo de tratamento', componente: 1 },
            'A16': { nome: 'Bebê irritável/choroso', componente: 1 },
            'A18': { nome: 'Preocupação com aparência', componente: 1 },
            'A20': { nome: 'Traumatismo/lesão NE', componente: 1 },
            'A21': { nome: 'Traumatismo múltiplo', componente: 1 },
            'A23': { nome: 'Fatores de risco NE', componente: 1 },
            'A24': { nome: 'Medo de doença NE', componente: 1 },
            'A25': { nome: 'Medo de câncer NE', componente: 1 },
            'A26': { nome: 'Medo de doença cardiovascular', componente: 1 },
            'A27': { nome: 'Medo de outras doenças', componente: 1 },
            'A28': { nome: 'Limitação/incapacidade funcional NE', componente: 1 },
            'A29': { nome: 'Sinais/sintomas gerais NE', componente: 1 },
            // Componente 2: Procedimentos Diagnósticos/Preventivos (30-49)
            'A30': { nome: 'Exame físico geral', componente: 2 },
            'A31': { nome: 'Exame de urina', componente: 2 },
            'A32': { nome: 'Exame de sangue', componente: 2 },
            'A33': { nome: 'Exame radiológico', componente: 2 },
            'A34': { nome: 'Teste de função', componente: 2 },
            'A35': { nome: 'Exame preventivo geral', componente: 2 },
            'A36': { nome: 'Medição de sinais vitais', componente: 2 },
            // Componente 3: Medicações/Tratamentos (50-59)
            'A50': { nome: 'Medicamento NE', componente: 3 },
            'A51': { nome: 'Analgésico', componente: 3 },
            'A52': { nome: 'Antibiótico', componente: 3 },
            'A53': { nome: 'Vacinação', componente: 3 },
            // Componente 4: Resultados de Exames (60-61)
            'A60': { nome: 'Resultado de exame normal', componente: 4 },
            'A61': { nome: 'Resultado de exame anormal', componente: 4 },
            // Componente 5: Administrativo (62)
            'A62': { nome: 'Procedimento administrativo', componente: 5 },
            // Componente 6: Encaminhamentos (63-69)
            'A63': { nome: 'Encaminhamento para especialista', componente: 6 },
            'A64': { nome: 'Encaminhamento para urgência', componente: 6 },
            'A65': { nome: 'Encaminhamento para internação', componente: 6 },
            'A66': { nome: 'Retorno/evolução', componente: 6 },
            'A67': { nome: 'Atestado médico', componente: 6 },
            'A68': { nome: 'Declaração de comparecimento', componente: 6 },
            'A69': { nome: 'Outros encaminhamentos', componente: 6 },
            // Componente 7: Doenças/Problemas (70-99)
            'A70': { nome: 'Tuberculose', componente: 7 },
            'A71': { nome: 'Infecção viral NE', componente: 7 },
            'A72': { nome: 'Varicela', componente: 7 },
            'A73': { nome: 'Sarampo', componente: 7 },
            'A74': { nome: 'Rubéola', componente: 7 },
            'A75': { nome: 'Caxumba', componente: 7 },
            'A76': { nome: 'Mononucleose', componente: 7 },
            'A77': { nome: 'Dengue e outras doenças virais NE', componente: 7 },
            'A78': { nome: 'Hanseníase e outras doenças infecciosas NE', componente: 7 },
            'A79': { nome: 'Infecção parasitária NE', componente: 7 },
            'A80': { nome: 'Traumatismo/lesão NE', componente: 7 },
            'A81': { nome: 'Intoxicação/efeito adverso', componente: 7 },
            'A82': { nome: 'Efeito colateral de tratamento', componente: 7 },
            'A83': { nome: 'Reação alérgica NE', componente: 7 },
            'A84': { nome: 'Corpo estranho NE', componente: 7 },
            'A85': { nome: 'Malformação congênita NE', componente: 7 },
            'A86': { nome: 'Neoplasia benigna NE', componente: 7 },
            'A87': { nome: 'Neoplasia maligna NE', componente: 7 },
            'A88': { nome: 'Síndrome de imunodeficiência', componente: 7 },
            'A90': { nome: 'Doença infecciosa NE', componente: 7 },
            'A91': { nome: 'Doença parasitária NE', componente: 7 },
            'A92': { nome: 'Alergia/reacção alérgica NE', componente: 7 },
            'A93': { nome: 'Doença causada por agente físico', componente: 7 },
            'A94': { nome: 'Morbidade perinatal NE', componente: 7 },
            'A95': { nome: 'Mortalidade perinatal', componente: 7 },
            'A96': { nome: 'Morte NE', componente: 7 },
            'A97': { nome: 'Sem doença / pessoa saudável', componente: 7 },
            'A98': { nome: 'Estado de saúde NE', componente: 7 },
            'A99': { nome: 'Outras doenças gerais NE', componente: 7 },
        }
    },

    // ===== CAPÍTULO B - SANGUE E ÓRGÃOS HEMATOPOIÉTICOS =====
    B: {
        nome: 'Sangue, Órgãos Hematopoiéticos e Linfáticos',
        descricao: 'Alterações do sangue, baço, medula óssea e sistema linfático',
        rubricas: {
            'B01': { nome: 'Gânglio linfático aumentado/doloroso', componente: 1 },
            'B02': { nome: 'Manchas/sinais de hemorragia', componente: 1 },
            'B03': { nome: 'Sinais/sintomas de anemia', componente: 1 },
            'B04': { nome: 'Sinais/sintomas de alteração sanguínea', componente: 1 },
            'B25': { nome: 'Medo de HIV/SIDA', componente: 1 },
            'B26': { nome: 'Medo de câncer no sangue/linfático', componente: 1 },
            'B27': { nome: 'Medo de outras doenças do sangue', componente: 1 },
            'B28': { nome: 'Limitação/incapacidade por doença do sangue', componente: 1 },
            'B29': { nome: 'Sinais/sintomas do sangue NE', componente: 1 },
            'B70': { nome: 'Infecção por HIV/SIDA', componente: 7 },
            'B71': { nome: 'Hepatite viral NE', componente: 7 },
            'B72': { nome: 'Hepatite A', componente: 7 },
            'B73': { nome: 'Hepatite B', componente: 7 },
            'B74': { nome: 'Hepatite C', componente: 7 },
            'B75': { nome: 'Outra hepatite viral', componente: 7 },
            'B76': { nome: 'Hepatite NE', componente: 7 },
            'B77': { nome: 'Doença linfática NE', componente: 7 },
            'B78': { nome: 'Anemia hereditária', componente: 7 },
            'B79': { nome: 'Outras malformações congênitas do sangue', componente: 7 },
            'B80': { nome: 'Anemia por deficiência de ferro', componente: 7 },
            'B81': { nome: 'Anemia perniciosa/deficiência de folatos', componente: 7 },
            'B82': { nome: 'Outras anemias NE', componente: 7 },
            'B83': { nome: 'Púrpura/defeitos de coagulação', componente: 7 },
            'B84': { nome: 'Alteração dos glóbulos brancos', componente: 7 },
            'B85': { nome: 'Leucemia', componente: 7 },
            'B86': { nome: 'Linfoma', componente: 7 },
            'B87': { nome: 'Esplenomegalia', componente: 7 },
            'B88': { nome: 'Doença da tireoide NE', componente: 7 },
            'B90': { nome: 'Infecção por HIV/SIDA', componente: 7 },
            'B99': { nome: 'Outras doenças do sangue/linfáticos/baço', componente: 7 },
        }
    },

    // ===== CAPÍTULO D - APARELHO DIGESTIVO =====
    D: {
        nome: 'Aparelho Digestivo',
        descricao: 'Problemas do sistema digestivo, boca, estômago, intestinos e anexos',
        rubricas: {
            'D01': { nome: 'Dor abdominal generalizada/cólicas', componente: 1 },
            'D02': { nome: 'Dor abdominal epigástrica', componente: 1 },
            'D03': { nome: 'Azia/queimação', componente: 1 },
            'D04': { nome: 'Dor anal/retal', componente: 1 },
            'D05': { nome: 'Irritação perianal', componente: 1 },
            'D06': { nome: 'Outras dores abdominais localizadas', componente: 1 },
            'D07': { nome: 'Dispepsia/indigestão', componente: 1 },
            'D08': { nome: 'Flatulência/gases/arrotos', componente: 1 },
            'D09': { nome: 'Náusea', componente: 1 },
            'D10': { nome: 'Vômito', componente: 1 },
            'D11': { nome: 'Diarreia', componente: 1 },
            'D12': { nome: 'Constipação', componente: 1 },
            'D13': { nome: 'Icterícia', componente: 1 },
            'D14': { nome: 'Hematêmese/vômito com sangue', componente: 1 },
            'D15': { nome: 'Melena', componente: 1 },
            'D16': { nome: 'Sangramento retal', componente: 1 },
            'D17': { nome: 'Incontinência fecal', componente: 1 },
            'D18': { nome: 'Dor de dente/gengiva', componente: 1 },
            'D19': { nome: 'Alterações nos dentes/gengivas', componente: 1 },
            'D20': { nome: 'Mudança de hábito intestinal', componente: 1 },
            'D23': { nome: 'Medo de câncer digestivo', componente: 1 },
            'D24': { nome: 'Medo de outras doenças digestivas', componente: 1 },
            'D25': { nome: 'Medo de hepatite', componente: 1 },
            'D26': { nome: 'Medo de outras doenças do fígado', componente: 1 },
            'D27': { nome: 'Medo de câncer do aparelho digestivo', componente: 1 },
            'D28': { nome: 'Limitação/incapacidade digestiva', componente: 1 },
            'D29': { nome: 'Sinais/sintomas digestivos NE', componente: 1 },
            'D30': { nome: 'Exame de fezes', componente: 2 },
            'D31': { nome: 'Endoscopia', componente: 2 },
            'D32': { nome: 'Exame radiológico do TGI', componente: 2 },
            'D33': { nome: 'Exame da cavidade oral', componente: 2 },
            'D34': { nome: 'Exame de função hepática', componente: 2 },
            'D35': { nome: 'Exame de prótese dentária', componente: 2 },
            'D50': { nome: 'Medicamento para o TGI', componente: 3 },
            'D51': { nome: 'Tratamento odontológico', componente: 3 },
            'D52': { nome: 'Orientação dietética', componente: 3 },
            'D53': { nome: 'Terapia de reposição', componente: 3 },
            'D62': { nome: 'Encaminhamento para odontologia', componente: 6 },
            'D63': { nome: 'Acompanhamento/evolução digestiva', componente: 6 },
            'D70': { nome: 'Doença infecciosa intestinal', componente: 7 },
            'D71': { nome: 'Parasitose intestinal', componente: 7 },
            'D72': { nome: 'Neoplasia benigna digestiva', componente: 7 },
            'D73': { nome: 'Neoplasia maligna digestiva', componente: 7 },
            'D74': { nome: 'Câncer de esôfago', componente: 7 },
            'D75': { nome: 'Câncer de estômago', componente: 7 },
            'D76': { nome: 'Câncer colorretal', componente: 7 },
            'D77': { nome: 'Outras neoplasias digestivas', componente: 7 },
            'D78': { nome: 'Doença da vesícula biliar', componente: 7 },
            'D79': { nome: 'Doença do pâncreas', componente: 7 },
            'D80': { nome: 'Doença hepática NE', componente: 7 },
            'D81': { nome: 'Cirrose hepática', componente: 7 },
            'D82': { nome: 'Doença do esôfago', componente: 7 },
            'D83': { nome: 'Úlcera gástrica/duodenal', componente: 7 },
            'D84': { nome: 'Gastrite/duodenite', componente: 7 },
            'D85': { nome: 'Doença do intestino delgado', componente: 7 },
            'D86': { nome: 'Doença do intestino grosso', componente: 7 },
            'D87': { nome: 'Doença do reto/ânus', componente: 7 },
            'D88': { nome: 'Hérnia diafragmática/hiatal', componente: 7 },
            'D89': { nome: 'Hérnia abdominal/inguinal', componente: 7 },
            'D90': { nome: 'Doença do estômago NE', componente: 7 },
            'D91': { nome: 'Doença da cavidade oral', componente: 7 },
            'D92': { nome: 'Doença do esôfago NE', componente: 7 },
            'D93': { nome: 'Síndrome do intestino irritável', componente: 7 },
            'D94': { nome: 'Doença intestinal inflamatória', componente: 7 },
            'D95': { nome: 'Diverticulose/diverticulite', componente: 7 },
            'D96': { nome: 'Doença hemorroidária', componente: 7 },
            'D97': { nome: 'Constipação crônica', componente: 7 },
            'D98': { nome: 'Doença do fígado NE', componente: 7 },
            'D99': { nome: 'Outras doenças digestivas', componente: 7 },
        }
    },

    // ===== CAPÍTULO F - OLHOS =====
    F: {
        nome: 'Olhos e Anexos',
        descricao: 'Problemas oftalmológicos e da visão',
        rubricas: {
            'F01': { nome: 'Dor ocular', componente: 1 },
            'F02': { nome: 'Vermelhidão ocular', componente: 1 },
            'F03': { nome: 'Secreção ocular', componente: 1 },
            'F04': { nome: 'Visão turva/embaçada', componente: 1 },
            'F05': { nome: 'Perda de visão', componente: 1 },
            'F06': { nome: 'Visão dupla/diplopia', componente: 1 },
            'F07': { nome: 'Fotofobia/sensibilidade à luz', componente: 1 },
            'F08': { nome: 'Corpo estranho no olho', componente: 1 },
            'F09': { nome: 'Sensação de corpo estranho', componente: 1 },
            'F10': { nome: 'Traumatismo ocular', componente: 1 },
            'F27': { nome: 'Medo de cegueira', componente: 1 },
            'F28': { nome: 'Limitação/incapacidade visual', componente: 1 },
            'F29': { nome: 'Sinais/sintomas oculares NE', componente: 1 },
            'F30': { nome: 'Avaliação visual/acuidade', componente: 2 },
            'F31': { nome: 'Teste de campo visual', componente: 2 },
            'F32': { nome: 'Fundo de olho', componente: 2 },
            'F33': { nome: 'Tonometria', componente: 2 },
            'F34': { nome: 'Exame com lâmpada de fenda', componente: 2 },
            'F35': { nome: 'Teste de refração', componente: 2 },
            'F50': { nome: 'Prescrição de lentes', componente: 3 },
            'F51': { nome: 'Colírio/medicação ocular', componente: 3 },
            'F52': { nome: 'Curativo ocular', componente: 3 },
            'F70': { nome: 'Conjuntivite', componente: 7 },
            'F71': { nome: 'Cevada/calázio', componente: 7 },
            'F72': { nome: 'Ceratite/úlcera de córnea', componente: 7 },
            'F73': { nome: 'Uveíte/irite', componente: 7 },
            'F74': { nome: 'Glaucoma', componente: 7 },
            'F75': { nome: 'Catarata', componente: 7 },
            'F76': { nome: 'Corpo estranho no olho', componente: 7 },
            'F77': { nome: 'Traumatismo ocular', componente: 7 },
            'F78': { nome: 'Descolamento de retina', componente: 7 },
            'F79': { nome: 'Retinopatia', componente: 7 },
            'F80': { nome: 'Amaurose/cegueira', componente: 7 },
            'F81': { nome: 'Estrabismo', componente: 7 },
            'F82': { nome: 'Erros de refração', componente: 7 },
            'F83': { nome: 'Astigmatismo', componente: 7 },
            'F84': { nome: 'Miopia', componente: 7 },
            'F85': { nome: 'Hipermetropia', componente: 7 },
            'F86': { nome: 'Presbiopia', componente: 7 },
            'F87': { nome: 'Ambliopia', componente: 7 },
            'F88': { nome: 'Nistagmo', componente: 7 },
            'F89': { nome: 'Pterígio', componente: 7 },
            'F90': { nome: 'Síndrome do olho seco', componente: 7 },
            'F91': { nome: 'Blefarite', componente: 7 },
            'F92': { nome: 'Dacriocistite', componente: 7 },
            'F99': { nome: 'Outras doenças oculares', componente: 7 },
        }
    },

    // ===== CAPÍTULO H - OUVIDOS =====
    H: {
        nome: 'Ouvidos e Audição',
        descricao: 'Problemas auditivos, do ouvido e equilíbrio',
        rubricas: {
            'H01': { nome: 'Dor de ouvido/otalgia', componente: 1 },
            'H02': { nome: 'Perda de audição', componente: 1 },
            'H03': { nome: 'Zumbido', componente: 1 },
            'H04': { nome: 'Secreção auricular', componente: 1 },
            'H05': { nome: 'Sangramento do ouvido', componente: 1 },
            'H06': { nome: 'Vertigem', componente: 1 },
            'H07': { nome: 'Prurido no ouvido', componente: 1 },
            'H08': { nome: 'Corpo estranho no ouvido', componente: 1 },
            'H09': { nome: 'Sensação de ouvido entupido', componente: 1 },
            'H10': { nome: 'Traumatismo auricular', componente: 1 },
            'H27': { nome: 'Medo de surdez', componente: 1 },
            'H28': { nome: 'Limitação/incapacidade auditiva', componente: 1 },
            'H29': { nome: 'Sinais/sintomas auditivos NE', componente: 1 },
            'H30': { nome: 'Audiometria/teste auditivo', componente: 2 },
            'H31': { nome: 'Otoscopia', componente: 2 },
            'H32': { nome: 'Teste de equilíbrio', componente: 2 },
            'H50': { nome: 'Remoção de cera/corpo estranho', componente: 3 },
            'H51': { nome: 'Medicação otológica', componente: 3 },
            'H70': { nome: 'Otite externa', componente: 7 },
            'H71': { nome: 'Otite média aguda', componente: 7 },
            'H72': { nome: 'Otite média crônica', componente: 7 },
            'H73': { nome: 'Otite média NE', componente: 7 },
            'H74': { nome: 'Otosclerose', componente: 7 },
            'H75': { nome: 'Perfuração timpânica', componente: 7 },
            'H76': { nome: 'Corpo estranho no ouvido', componente: 7 },
            'H77': { nome: 'Traumatismo auricular', componente: 7 },
            'H78': { nome: 'Traumatismo superficial do ouvido', componente: 7 },
            'H79': { nome: 'Cerume impactado', componente: 7 },
            'H80': { nome: 'Doença de Menière', componente: 7 },
            'H81': { nome: 'Vertigem posicional', componente: 7 },
            'H82': { nome: 'Surdez NE', componente: 7 },
            'H83': { nome: 'Surdez condutiva', componente: 7 },
            'H84': { nome: 'Surdez neurossensorial', componente: 7 },
            'H85': { nome: 'Zumbido NE', componente: 7 },
            'H86': { nome: 'Perda auditiva NE', componente: 7 },
            'H99': { nome: 'Outras doenças do ouvido', componente: 7 },
        }
    },

    // ===== CAPÍTULO K - APARELHO CIRCULATÓRIO =====
    K: {
        nome: 'Aparelho Circulatório',
        descricao: 'Problemas cardiovasculares, circulatórios e vasculares',
        rubricas: {
            'K01': { nome: 'Dor torácica/angina', componente: 1 },
            'K02': { nome: 'Palpitações', componente: 1 },
            'K03': { nome: 'Edema de membros', componente: 1 },
            'K04': { nome: 'Claudicação intermitente', componente: 1 },
            'K05': { nome: 'Cianose', componente: 1 },
            'K06': { nome: 'Varizes', componente: 1 },
            'K07': { nome: 'Pulso periférico alterado', componente: 1 },
            'K08': { nome: 'Pressão arterial elevada', componente: 1 },
            'K09': { nome: 'Pressão arterial baixa', componente: 1 },
            'K10': { nome: 'Dor nas pernas ao caminhar', componente: 1 },
            'K11': { nome: 'Dor torácica NE', componente: 1 },
            'K24': { nome: 'Medo de infarto/doença cardíaca', componente: 1 },
            'K25': { nome: 'Medo de AVC', componente: 1 },
            'K26': { nome: 'Medo de hipertensão', componente: 1 },
            'K27': { nome: 'Medo de doenças cardiovasculares', componente: 1 },
            'K28': { nome: 'Limitação/incapacidade cardiovascular', componente: 1 },
            'K29': { nome: 'Sinais/sintomas cardiovasculares NE', componente: 1 },
            'K30': { nome: 'Eletrocardiograma', componente: 2 },
            'K31': { nome: 'Teste de esforço', componente: 2 },
            'K32': { nome: 'Ecocardiograma', componente: 2 },
            'K33': { nome: 'Holter/Ritmo cardíaco', componente: 2 },
            'K34': { nome: 'Doppler vascular', componente: 2 },
            'K35': { nome: 'Angiografia', componente: 2 },
            'K36': { nome: 'MAPA/Medição pressão', componente: 2 },
            'K50': { nome: 'Medicação cardiovascular', componente: 3 },
            'K51': { nome: 'Anti-hipertensivo', componente: 3 },
            'K52': { nome: 'Diurético', componente: 3 },
            'K53': { nome: 'Anticoagulante', componente: 3 },
            'K54': { nome: 'Antiarrítmico', componente: 3 },
            'K55': { nome: 'Nitrato', componente: 3 },
            'K56': { nome: 'Hipolipemiante', componente: 3 },
            'K57': { nome: 'Reanimação cardíaca', componente: 3 },
            'K70': { nome: 'Infarto agudo do miocárdio', componente: 7 },
            'K71': { nome: 'Angina estável', componente: 7 },
            'K72': { nome: 'Angina instável', componente: 7 },
            'K73': { nome: 'Insuficiência cardíaca', componente: 7 },
            'K74': { nome: 'Arritmia', componente: 7 },
            'K75': { nome: 'Fibrilação atrial', componente: 7 },
            'K76': { nome: 'Hipertensão arterial', componente: 7 },
            'K77': { nome: 'Hipotensão', componente: 7 },
            'K78': { nome: 'Doença cardíaca valvular', componente: 7 },
            'K79': { nome: 'Doença cardíaca reumática', componente: 7 },
            'K80': { nome: 'Doença vascular periférica', componente: 7 },
            'K81': { nome: 'Trombose venosa profunda', componente: 7 },
            'K82': { nome: 'Embolia pulmonar', componente: 7 },
            'K83': { nome: 'Varizes', componente: 7 },
            'K84': { nome: 'AVC/Acidente vascular cerebral', componente: 7 },
            'K85': { nome: 'Ataque isquêmico transitório', componente: 7 },
            'K86': { nome: 'Aneurisma', componente: 7 },
            'K87': { nome: 'Doença aterosclerótica', componente: 7 },
            'K88': { nome: 'Pericardite', componente: 7 },
            'K89': { nome: 'Endocardite', componente: 7 },
            'K90': { nome: 'Miocardite', componente: 7 },
            'K91': { nome: 'Cardiomiopatia', componente: 7 },
            'K92': { nome: 'Doença cardíaca congênita', componente: 7 },
            'K93': { nome: 'Hipertensão pulmonar', componente: 7 },
            'K94': { nome: 'Síndrome de Raynaud', componente: 7 },
            'K95': { nome: 'Linfedema', componente: 7 },
            'K99': { nome: 'Outras doenças cardiovasculares', componente: 7 },
        }
    },

    // ===== CAPÍTULO L - SISTEMA MUSCULOESQUELÉTICO =====
    L: {
        nome: 'Sistema Musculoesquelético',
        descricao: 'Problemas de ossos, articulações, músculos e tecidos moles',
        rubricas: {
            'L01': { nome: 'Dor cervical', componente: 1 },
            'L02': { nome: 'Dor dorsal', componente: 1 },
            'L03': { nome: 'Dor lombar', componente: 1 },
            'L04': { nome: 'Dor torácica musculoesquelética', componente: 1 },
            'L05': { nome: 'Dor generalizada', componente: 1 },
            'L07': { nome: 'Rigidez articular', componente: 1 },
            'L08': { nome: 'Dor articular', componente: 1 },
            'L09': { nome: 'Inchaço articular', componente: 1 },
            'L10': { nome: 'Dor muscular', componente: 1 },
            'L11': { nome: 'Dor óssea', componente: 1 },
            'L12': { nome: 'Traumatismo musculoesquelético', componente: 1 },
            'L13': { nome: 'Distensão/torção', componente: 1 },
            'L14': { nome: 'Entorse', componente: 1 },
            'L15': { nome: 'Fratura', componente: 1 },
            'L16': { nome: 'Dor no ombro', componente: 1 },
            'L17': { nome: 'Dor no cotovelo/braço', componente: 1 },
            'L18': { nome: 'Dor no punho/mão', componente: 1 },
            'L19': { nome: 'Dor no quadril/anca', componente: 1 },
            'L20': { nome: 'Dor no joelho', componente: 1 },
            'L21': { nome: 'Dor no tornozelo/pé', componente: 1 },
            'L22': { nome: 'Claudicação', componente: 1 },
            'L23': { nome: 'Limitação de movimento', componente: 1 },
            'L24': { nome: 'Queda', componente: 1 },
            'L26': { nome: 'Medo de câncer musculoesquelético', componente: 1 },
            'L27': { nome: 'Medo de outras doenças musculoesqueléticas', componente: 1 },
            'L28': { nome: 'Limitação/incapacidade musculoesquelética', componente: 1 },
            'L29': { nome: 'Sinais/sintomas musculoesqueléticos NE', componente: 1 },
            'L30': { nome: 'Raio-X', componente: 2 },
            'L31': { nome: 'Ressonância magnética', componente: 2 },
            'L32': { nome: 'Tomografia computadorizada', componente: 2 },
            'L33': { nome: 'Densitometria óssea', componente: 2 },
            'L34': { nome: 'Articulação de movimento', componente: 2 },
            'L35': { nome: 'Exame ortopédico', componente: 2 },
            'L50': { nome: 'Analgésico/anti-inflamatório', componente: 3 },
            'L51': { nome: 'Imobilização/gesso', componente: 3 },
            'L52': { nome: 'Fisioterapia', componente: 3 },
            'L53': { nome: 'Orientação postural', componente: 3 },
            'L54': { nome: 'Procedimento ortopédico', componente: 3 },
            'L55': { nome: 'Injeção intra-articular', componente: 3 },
            'L62': { nome: 'Encaminhamento para fisioterapia', componente: 6 },
            'L63': { nome: 'Encaminhamento para ortopedia', componente: 6 },
            'L70': { nome: 'Traumatismo musculoesquelético', componente: 7 },
            'L71': { nome: 'Fratura NE', componente: 7 },
            'L72': { nome: 'Entorse/torção', componente: 7 },
            'L73': { nome: 'Lesão muscular', componente: 7 },
            'L74': { nome: 'Luxação', componente: 7 },
            'L75': { nome: 'Hérnia de disco', componente: 7 },
            'L76': { nome: 'Osteoartrite', componente: 7 },
            'L77': { nome: 'Artrite reumatoide', componente: 7 },
            'L78': { nome: 'Artrite NE', componente: 7 },
            'L79': { nome: 'Osteoporose', componente: 7 },
            'L80': { nome: 'Bursite/tendinite', componente: 7 },
            'L81': { nome: 'Síndrome do túnel do carpo', componente: 7 },
            'L82': { nome: 'Epicondilite', componente: 7 },
            'L83': { nome: 'Ombro congelado/capsulite', componente: 7 },
            'L84': { nome: 'Espondilose', componente: 7 },
            'L85': { nome: 'Escoliose/cifose', componente: 7 },
            'L86': { nome: 'Doença óssea NE', componente: 7 },
            'L87': { nome: 'Poliomielite', componente: 7 },
            'L88': { nome: 'Osteomielite', componente: 7 },
            'L89': { nome: 'Neoplasia óssea', componente: 7 },
            'L90': { nome: 'Fibromialgia', componente: 7 },
            'L91': { nome: 'Síndrome da dor miofascial', componente: 7 },
            'L92': { nome: 'Dismorfia musculoesquelética', componente: 7 },
            'L93': { nome: 'Doença da coluna', componente: 7 },
            'L94': { nome: 'Doença articular degenerativa', componente: 7 },
            'L95': { nome: 'Gota', componente: 7 },
            'L96': { nome: 'Doença do disco intervertebral', componente: 7 },
            'L97': { nome: 'Dismorfia congênita musculoesquelética', componente: 7 },
            'L98': { nome: 'Síndrome de compressão radicular', componente: 7 },
            'L99': { nome: 'Outras doenças musculoesqueléticas', componente: 7 },
        }
    },

    // ===== CAPÍTULO N - SISTEMA NERVOSO =====
    N: {
        nome: 'Sistema Nervoso',
        descricao: 'Problemas neurológicos, nervos e sistema nervoso',
        rubricas: {
            'N01': { nome: 'Cefaleia', componente: 1 },
            'N02': { nome: 'Enxaqueca', componente: 1 },
            'N03': { nome: 'Dor facial', componente: 1 },
            'N04': { nome: 'Dor neuropática', componente: 1 },
            'N05': { nome: 'Parestesia/formigamento', componente: 1 },
            'N06': { nome: 'Anestesia/perda de sensibilidade', componente: 1 },
            'N07': { nome: 'Convulsões/ataques', componente: 1 },
            'N08': { nome: 'Movimentos involuntários', componente: 1 },
            'N16': { nome: 'Alteração olfato/paladar', componente: 1 },
            'N17': { nome: 'Vertigem/tontura', componente: 1 },
            'N18': { nome: 'Paralisia/fraqueza', componente: 1 },
            'N19': { nome: 'Alteração da fala', componente: 1 },
            'N20': { nome: 'Alteração da marcha', componente: 1 },
            'N26': { nome: 'Medo de câncer neurológico', componente: 1 },
            'N27': { nome: 'Medo de outras doenças neurológicas', componente: 1 },
            'N28': { nome: 'Limitação/incapacidade neurológica', componente: 1 },
            'N29': { nome: 'Sinais/sintomas neurológicos NE', componente: 1 },
            'N30': { nome: 'Exame neurológico', componente: 2 },
            'N31': { nome: 'Tomografia de crânio', componente: 2 },
            'N32': { nome: 'Ressonância de crânio', componente: 2 },
            'N33': { nome: 'Eletroencefalograma', componente: 2 },
            'N34': { nome: 'Punção lombar', componente: 2 },
            'N35': { nome: 'Eletroneuromiografia', componente: 2 },
            'N50': { nome: 'Medicação neurológica', componente: 3 },
            'N51': { nome: 'Anticonvulsivante', componente: 3 },
            'N52': { nome: 'Analgésico neuropático', componente: 3 },
            'N70': { nome: 'Poliomielite', componente: 7 },
            'N71': { nome: 'Meningite/encefalite', componente: 7 },
            'N72': { nome: 'Tétano', componente: 7 },
            'N73': { nome: 'Outras infecções neurológicas', componente: 7 },
            'N74': { nome: 'Neoplasia maligna do sistema nervoso', componente: 7 },
            'N75': { nome: 'Neoplasia benigna do sistema nervoso', componente: 7 },
            'N76': { nome: 'Neoplasia neurológica NE', componente: 7 },
            'N79': { nome: 'Concussão', componente: 7 },
            'N80': { nome: 'Traumatismo craniano', componente: 7 },
            'N81': { nome: 'Outras lesões neurológicas', componente: 7 },
            'N85': { nome: 'Malformação congênita neurológica', componente: 7 },
            'N86': { nome: 'Esclerose múltipla', componente: 7 },
            'N87': { nome: 'Parkinsonismo', componente: 7 },
            'N88': { nome: 'Epilepsia', componente: 7 },
            'N89': { nome: 'Enxaqueca', componente: 7 },
            'N90': { nome: 'Cefaleia de cluster', componente: 7 },
            'N91': { nome: 'Paralisia facial/Paralisia de Bell', componente: 7 },
            'N92': { nome: 'Neuralgia do trigêmeo', componente: 7 },
            'N93': { nome: 'Síndrome do túnel do carpo', componente: 7 },
            'N94': { nome: 'Neurite/neuropatia periférica', componente: 7 },
            'N95': { nome: 'Cefaleia tensional', componente: 7 },
            'N96': { nome: 'Neuralgia NE', componente: 7 },
            'N97': { nome: 'Cefaleia NE', componente: 7 },
            'N98': { nome: 'Neuropatia NE', componente: 7 },
            'N99': { nome: 'Outras doenças neurológicas', componente: 7 },
        }
    },

    // ===== CAPÍTULO P - PROBLEMAS PSICOLÓGICOS =====
    P: {
        nome: 'Problemas Psicológicos',
        descricao: 'Transtornos mentais, emocionais e comportamentais',
        rubricas: {
            'P01': { nome: 'Ansiedade/nervosismo/tensão', componente: 1 },
            'P02': { nome: 'Reação aguda ao estresse', componente: 1 },
            'P03': { nome: 'Tristeza/depressão', componente: 1 },
            'P04': { nome: 'Irritabilidade/raiva', componente: 1 },
            'P05': { nome: 'Sensação/comportamento senil', componente: 1 },
            'P06': { nome: 'Distúrbio do sono', componente: 1 },
            'P07': { nome: 'Diminuição do desejo sexual', componente: 1 },
            'P08': { nome: 'Diminuição da satisfação sexual', componente: 1 },
            'P09': { nome: 'Preocupação com preferência sexual', componente: 1 },
            'P10': { nome: 'Gagueira/tiques', componente: 1 },
            'P11': { nome: 'Problemas alimentares infantis', componente: 1 },
            'P12': { nome: 'Enurese/molhar a cama', componente: 1 },
            'P13': { nome: 'Encoprese/incontinência fecal', componente: 1 },
            'P15': { nome: 'Abuso crônico de álcool', componente: 1 },
            'P16': { nome: 'Abuso agudo de álcool', componente: 1 },
            'P17': { nome: 'Tabagismo', componente: 1 },
            'P18': { nome: 'Abuso de medicação', componente: 1 },
            'P19': { nome: 'Abuso de drogas', componente: 1 },
            'P20': { nome: 'Alterações da memória', componente: 1 },
            'P22': { nome: 'Comportamento infantil anormal', componente: 1 },
            'P23': { nome: 'Comportamento adolescente anormal', componente: 1 },
            'P24': { nome: 'Dificuldade de aprendizagem', componente: 1 },
            'P25': { nome: 'Problemas da vida adulta', componente: 1 },
            'P27': { nome: 'Medo de transtornos mentais', componente: 1 },
            'P28': { nome: 'Limitação/incapacidade psicológica', componente: 1 },
            'P29': { nome: 'Sinais/sintomas psicológicos NE', componente: 1 },
            'P30': { nome: 'Avaliação psicológica', componente: 2 },
            'P31': { nome: 'Teste cognitivo', componente: 2 },
            'P32': { nome: 'Escala de depressão/ansiedade', componente: 2 },
            'P33': { nome: 'Teste de personalidade', componente: 2 },
            'P50': { nome: 'Psicoterapia', componente: 3 },
            'P51': { nome: 'Aconselhamento', componente: 3 },
            'P52': { nome: 'Medicamento psicotrópico', componente: 3 },
            'P53': { nome: 'Antidepressivo', componente: 3 },
            'P54': { nome: 'Ansiolítico', componente: 3 },
            'P55': { nome: 'Antipsicótico', componente: 3 },
            'P56': { nome: 'Estabilizador de humor', componente: 3 },
            'P57': { nome: 'Desintoxicação', componente: 3 },
            'P58': { nome: 'Internação psiquiátrica', componente: 3 },
            'P62': { nome: 'Encaminhamento psicológico', componente: 6 },
            'P63': { nome: 'Encaminhamento psiquiátrico', componente: 6 },
            'P64': { nome: 'Acompanhamento psicológico', componente: 6 },
            'P70': { nome: 'Demência', componente: 7 },
            'P71': { nome: 'Psicose orgânica NE', componente: 7 },
            'P72': { nome: 'Esquizofrenia', componente: 7 },
            'P73': { nome: 'Psicose afetiva', componente: 7 },
            'P74': { nome: 'Transtorno ansioso', componente: 7 },
            'P75': { nome: 'Somatização', componente: 7 },
            'P76': { nome: 'Transtorno depressivo', componente: 7 },
            'P77': { nome: 'Suicídio/tentativa de suicídio', componente: 7 },
            'P78': { nome: 'Neurastenia', componente: 7 },
            'P79': { nome: 'Fobia/transtorno compulsivo', componente: 7 },
            'P80': { nome: 'Transtorno de personalidade', componente: 7 },
            'P81': { nome: 'Transtorno hipercinético', componente: 7 },
            'P82': { nome: 'Estresse pós-traumático', componente: 7 },
            'P83': { nome: 'Transtorno de adaptação', componente: 7 },
            'P84': { nome: 'Transtorno bipolar', componente: 7 },
            'P85': { nome: 'Retardo/atraso mental', componente: 7 },
            'P86': { nome: 'Anorexia nervosa/bulimia', componente: 7 },
            'P87': { nome: 'Transtorno de conduta', componente: 7 },
            'P88': { nome: 'Transtorno de pânico', componente: 7 },
            'P89': { nome: 'Transtorno de estresse agudo', componente: 7 },
            'P90': { nome: 'Transtorno de ansiedade generalizada', componente: 7 },
            'P91': { nome: 'Transtorno dissociativo', componente: 7 },
            'P92': { nome: 'Transtorno de conversão', componente: 7 },
            'P93': { nome: 'Transtorno factício', componente: 7 },
            'P94': { nome: 'Transtorno do sono NE', componente: 7 },
            'P95': { nome: 'Transtorno de déficit de atenção', componente: 7 },
            'P96': { nome: 'Abuso de álcool', componente: 7 },
            'P97': { nome: 'Abuso de drogas', componente: 7 },
            'P98': { nome: 'Transtorno alimentar NE', componente: 7 },
            'P99': { nome: 'Outros transtornos psicológicos', componente: 7 },
        }
    },

    // ===== CAPÍTULO R - APARELHO RESPIRATÓRIO =====
    R: {
        nome: 'Aparelho Respiratório',
        descricao: 'Problemas do sistema respiratório, pulmões e vias aéreas',
        rubricas: {
            'R01': { nome: 'Dor respiratória', componente: 1 },
            'R02': { nome: 'Dispneia/falta de ar', componente: 1 },
            'R03': { nome: 'Sibilo/chiado', componente: 1 },
            'R04': { nome: 'Tosse', componente: 1 },
            'R05': { nome: 'Expectoração', componente: 1 },
            'R06': { nome: 'Epistaxe/sangramento nasal', componente: 1 },
            'R07': { nome: 'Espirro', componente: 1 },
            'R08': { nome: 'Congestão nasal', componente: 1 },
            'R09': { nome: 'Secreção nasal', componente: 1 },
            'R10': { nome: 'Dor de garganta', componente: 1 },
            'R11': { nome: 'Rouquidão', componente: 1 },
            'R12': { nome: 'Apneia', componente: 1 },
            'R13': { nome: 'Dor torácica respiratória', componente: 1 },
            'R14': { nome: 'Hematêmese/hemoptise', componente: 1 },
            'R15': { nome: 'Cianose', componente: 1 },
            'R16': { nome: 'Sensação de corpo estranho', componente: 1 },
            'R17': { nome: 'Problema respiratório NE', componente: 1 },
            'R24': { nome: 'Medo de câncer respiratório', componente: 1 },
            'R25': { nome: 'Medo de outra doença respiratória', componente: 1 },
            'R26': { nome: 'Medo de asma', componente: 1 },
            'R27': { nome: 'Medo de DPOC', componente: 1 },
            'R28': { nome: 'Limitação/incapacidade respiratória', componente: 1 },
            'R29': { nome: 'Sinais/sintomas respiratórios NE', componente: 1 },
            'R30': { nome: 'Raio-X de tórax', componente: 2 },
            'R31': { nome: 'Espirometria/teste pulmonar', componente: 2 },
            'R32': { nome: 'Gasometria', componente: 2 },
            'R33': { nome: 'Cultura de escarro', componente: 2 },
            'R34': { nome: 'Teste de alergia', componente: 2 },
            'R35': { nome: 'Oximetria de pulso', componente: 2 },
            'R36': { nome: 'Broncoscopia', componente: 2 },
            'R37': { nome: 'Rinoscopia', componente: 2 },
            'R50': { nome: 'Broncodilatador', componente: 3 },
            'R51': { nome: 'Antibiótico respiratório', componente: 3 },
            'R52': { nome: 'Expectorante', componente: 3 },
            'R53': { nome: 'Antialérgico', componente: 3 },
            'R54': { nome: 'Corticosteroide inalatório', componente: 3 },
            'R55': { nome: 'Oxigenoterapia', componente: 3 },
            'R56': { nome: 'Vacinação', componente: 3 },
            'R57': { nome: 'Inalação', componente: 3 },
            'R58': { nome: 'Drenagem postural', componente: 3 },
            'R62': { nome: 'Encaminhamento pneumologia', componente: 6 },
            'R63': { nome: 'Acompanhamento respiratório', componente: 6 },
            'R70': { nome: 'Infecção respiratória alta', componente: 7 },
            'R71': { nome: 'Coqueluche/pertussis', componente: 7 },
            'R72': { nome: 'Infecção estreptocócica de orofaringe', componente: 7 },
            'R73': { nome: 'Abscesso peritonsilar', componente: 7 },
            'R74': { nome: 'Infecção respiratória aguda', componente: 7 },
            'R75': { nome: 'Sinusite aguda', componente: 7 },
            'R76': { nome: 'Amigdalite aguda', componente: 7 },
            'R77': { nome: 'Laringite/traqueíte aguda', componente: 7 },
            'R78': { nome: 'Bronquite/bronquiolite aguda', componente: 7 },
            'R79': { nome: 'Bronquite crônica', componente: 7 },
            'R80': { nome: 'Gripe/influenza', componente: 7 },
            'R81': { nome: 'Pneumonia', componente: 7 },
            'R82': { nome: 'Pleurite/derrame pleural', componente: 7 },
            'R83': { nome: 'Outra infecção respiratória', componente: 7 },
            'R84': { nome: 'Neoplasia maligna de brônquios/pulmão', componente: 7 },
            'R85': { nome: 'Neoplasia benigna respiratória', componente: 7 },
            'R86': { nome: 'Asma', componente: 7 },
            'R87': { nome: 'DPOC/doença pulmonar obstrutiva', componente: 7 },
            'R88': { nome: 'Enfisema', componente: 7 },
            'R89': { nome: 'Corpo estranho no trato respiratório', componente: 7 },
            'R90': { nome: 'Traumatismo torácico', componente: 7 },
            'R91': { nome: 'Doença pulmonar NE', componente: 7 },
            'R92': { nome: 'Apneia do sono', componente: 7 },
            'R93': { nome: 'Fibrose pulmonar', componente: 7 },
            'R94': { nome: 'Doença pulmonar intersticial', componente: 7 },
            'R95': { nome: 'Sarcoidose', componente: 7 },
            'R96': { nome: 'Tuberculose', componente: 7 },
            'R97': { nome: 'Doença respiratória NE', componente: 7 },
            'R98': { nome: 'Rinite alérgica', componente: 7 },
            'R99': { nome: 'Outras doenças respiratórias', componente: 7 },
        }
    },

    // ===== CAPÍTULO S - PELE =====
    S: {
        nome: 'Pele e Anexos',
        descricao: 'Problemas dermatológicos e da pele',
        rubricas: {
            'S01': { nome: 'Erupção cutânea', componente: 1 },
            'S02': { nome: 'Prurido/coceira', componente: 1 },
            'S03': { nome: 'Verrugas', componente: 1 },
            'S04': { nome: 'Tumor/inchaço localizado', componente: 1 },
            'S05': { nome: 'Tumor/inchaço generalizado', componente: 1 },
            'S06': { nome: 'Erupção cutânea localizada', componente: 1 },
            'S07': { nome: 'Erupção cutânea generalizada', componente: 1 },
            'S08': { nome: 'Alteração da cor da pele', componente: 1 },
            'S09': { nome: 'Infecção dos dedos', componente: 1 },
            'S10': { nome: 'Furunculose/carbúnculo', componente: 1 },
            'S11': { nome: 'Infecção pós-traumática', componente: 1 },
            'S12': { nome: 'Picada/mordedura de inseto', componente: 1 },
            'S13': { nome: 'Mordedura animal/humana', componente: 1 },
            'S14': { nome: 'Queimadura/escaldão', componente: 1 },
            'S15': { nome: 'Corpo estranho na pele', componente: 1 },
            'S16': { nome: 'Traumatismo/contusão', componente: 1 },
            'S17': { nome: 'Abrasão/arranhão/bolhas', componente: 1 },
            'S18': { nome: 'Laceração/corte', componente: 1 },
            'S19': { nome: 'Outra lesão cutânea', componente: 1 },
            'S20': { nome: 'Calos/calosidades', componente: 1 },
            'S21': { nome: 'Alteração da textura da pele', componente: 1 },
            'S22': { nome: 'Alteração das unhas', componente: 1 },
            'S23': { nome: 'Queda de cabelo/calvície', componente: 1 },
            'S24': { nome: 'Sinais/sintomas de cabelo/couro cabeludo', componente: 1 },
            'S25': { nome: 'Medo de câncer de pele', componente: 1 },
            'S26': { nome: 'Medo de outras doenças da pele', componente: 1 },
            'S27': { nome: 'Limitação/incapacidade dermatológica', componente: 1 },
            'S28': { nome: 'Sinais/sintomas dermatológicos NE', componente: 1 },
            'S29': { nome: 'Sinais/sintomas da pele NE', componente: 1 },
            'S30': { nome: 'Biopsia de pele', componente: 2 },
            'S31': { nome: 'Cultura de pele', componente: 2 },
            'S32': { nome: 'Teste de alergia cutânea', componente: 2 },
            'S33': { nome: 'Exame dermatoscópico', componente: 2 },
            'S50': { nome: 'Medicação tópica', componente: 3 },
            'S51': { nome: 'Curativo', componente: 3 },
            'S52': { nome: 'Crioterapia', componente: 3 },
            'S53': { nome: 'Excisão de lesão', componente: 3 },
            'S54': { nome: 'Drenagem de abscesso', componente: 3 },
            'S55': { nome: 'Eletrocauterização', componente: 3 },
            'S56': { nome: 'Laserterapia', componente: 3 },
            'S70': { nome: 'Infecção cutânea', componente: 7 },
            'S71': { nome: 'Impetigo', componente: 7 },
            'S72': { nome: 'Celulite', componente: 7 },
            'S73': { nome: 'Abscesso cutâneo', componente: 7 },
            'S74': { nome: 'Foliculite', componente: 7 },
            'S75': { nome: 'Dermatite atópica/eczema', componente: 7 },
            'S76': { nome: 'Dermatite de contato', componente: 7 },
            'S77': { nome: 'Dermatite seborreica', componente: 7 },
            'S78': { nome: 'Dermatite NE', componente: 7 },
            'S79': { nome: 'Urticária', componente: 7 },
            'S80': { nome: 'Psoríase', componente: 7 },
            'S81': { nome: 'Verruga', componente: 7 },
            'S82': { nome: 'Micose/oncocercose', componente: 7 },
            'S83': { nome: 'Escabiose/sarna', componente: 7 },
            'S84': { nome: 'Piodermite', componente: 7 },
            'S85': { nome: 'Carcinoma basocelular', componente: 7 },
            'S86': { nome: 'Carcinoma espinocelular', componente: 7 },
            'S87': { nome: 'Melanoma', componente: 7 },
            'S88': { nome: 'Neoplasia benigna de pele', componente: 7 },
            'S89': { nome: 'Ceratose actínica', componente: 7 },
            'S90': { nome: 'Vitiligo', componente: 7 },
            'S91': { nome: 'Acne', componente: 7 },
            'S92': { nome: 'Alopecia', componente: 7 },
            'S93': { nome: 'Dermatofitose', componente: 7 },
            'S94': { nome: 'Eritema multiforme', componente: 7 },
            'S95': { nome: 'Pênfigo', componente: 7 },
            'S96': { nome: 'Lúpus eritematoso', componente: 7 },
            'S97': { nome: 'Esclerodermia', componente: 7 },
            'S98': { nome: 'Doença da unha', componente: 7 },
            'S99': { nome: 'Outras doenças da pele', componente: 7 },
        }
    },

    // ===== CAPÍTULO T - ENDÓCRINO E METABÓLICO =====
    T: {
        nome: 'Endócrino, Metabólico e Nutricional',
        descricao: 'Problemas endócrinos, metabólicos e nutricionais',
        rubricas: {
            'T01': { nome: 'Sede/polidipsia', componente: 1 },
            'T02': { nome: 'Perda de peso', componente: 1 },
            'T03': { nome: 'Ganho de peso', componente: 1 },
            'T04': { nome: 'Poliúria', componente: 1 },
            'T05': { nome: 'Aumento de apetite', componente: 1 },
            'T06': { nome: 'Perda de apetite', componente: 1 },
            'T07': { nome: 'Alteração da tireoide', componente: 1 },
            'T08': { nome: 'Alteração da pele', componente: 1 },
            'T09': { nome: 'Alteração do suor', componente: 1 },
            'T10': { nome: 'Retardo de crescimento', componente: 1 },
            'T11': { nome: 'Alteração de desenvolvimento', componente: 1 },
            'T26': { nome: 'Medo de diabetes', componente: 1 },
            'T27': { nome: 'Medo de outras doenças endócrinas', componente: 1 },
            'T28': { nome: 'Medo de obesidade', componente: 1 },
            'T29': { nome: 'Sinais/sintomas endócrinos NE', componente: 1 },
            'T30': { nome: 'Glicemia capilar', componente: 2 },
            'T31': { nome: 'Curva glicêmica', componente: 2 },
            'T32': { nome: 'Dosagem hormonal', componente: 2 },
            'T33': { nome: 'Teste de função tireoidiana', componente: 2 },
            'T34': { nome: 'Hemoglobina glicada', componente: 2 },
            'T35': { nome: 'Teste de função adrenal', componente: 2 },
            'T36': { nome: 'Avaliação nutricional', componente: 2 },
            'T50': { nome: 'Antidiabético', componente: 3 },
            'T51': { nome: 'Insulina', componente: 3 },
            'T52': { nome: 'Hormônio tireoidiano', componente: 3 },
            'T53': { nome: 'Corticosteroide', componente: 3 },
            'T54': { nome: 'Suplemento nutricional', componente: 3 },
            'T55': { nome: 'Dieta', componente: 3 },
            'T56': { nome: 'Orientação nutricional', componente: 3 },
            'T57': { nome: 'Terapia de reposição hormonal', componente: 3 },
            'T62': { nome: 'Encaminhamento endócrino', componente: 6 },
            'T63': { nome: 'Acompanhamento metabólico', componente: 6 },
            'T70': { nome: 'Diabetes mellitus', componente: 7 },
            'T71': { nome: 'Diabetes tipo 1', componente: 7 },
            'T72': { nome: 'Diabetes tipo 2', componente: 7 },
            'T73': { nome: 'Hipotireoidismo', componente: 7 },
            'T74': { nome: 'Hipertireoidismo', componente: 7 },
            'T75': { nome: 'Doença de Hashimoto', componente: 7 },
            'T76': { nome: 'Obesidade', componente: 7 },
            'T77': { nome: 'Desnutrição', componente: 7 },
            'T78': { nome: 'Deficiência de vitaminas', componente: 7 },
            'T79': { nome: 'Doença da paratireoide', componente: 7 },
            'T80': { nome: 'Doença da adrenal', componente: 7 },
            'T81': { nome: 'Síndrome de Cushing', componente: 7 },
            'T82': { nome: 'Síndrome metabólica', componente: 7 },
            'T83': { nome: 'Dislipidemia', componente: 7 },
            'T84': { nome: 'Hiperuricemia/gota', componente: 7 },
            'T85': { nome: 'Doença da glândula pituitária', componente: 7 },
            'T86': { nome: 'Distúrbio eletrolítico', componente: 7 },
            'T87': { nome: 'Desidratação', componente: 7 },
            'T88': { nome: 'Intolerância à lactose', componente: 7 },
            'T89': { nome: 'Doença celíaca', componente: 7 },
            'T90': { nome: 'Diabetes gestacional', componente: 7 },
            'T91': { nome: 'Hipoglicemia', componente: 7 },
            'T92': { nome: 'Hiperglicemia', componente: 7 },
            'T93': { nome: 'Doença da tireoide NE', componente: 7 },
            'T94': { nome: 'Distúrbio alimentar NE', componente: 7 },
            'T95': { nome: 'Doença endócrina NE', componente: 7 },
            'T96': { nome: 'Distúrbio metabólico NE', componente: 7 },
            'T97': { nome: 'Deficiência de ferro', componente: 7 },
            'T98': { nome: 'Deficiência de vitaminas NE', componente: 7 },
            'T99': { nome: 'Outras doenças endócrinas', componente: 7 },
        }
    },

    // ===== CAPÍTULO U - APARELHO URINÁRIO =====
    U: {
        nome: 'Aparelho Urinário',
        descricao: 'Problemas do sistema urinário, rins e bexiga',
        rubricas: {
            'U01': { nome: 'Dor/queimação ao urinar', componente: 1 },
            'U02': { nome: 'Urgência miccional', componente: 1 },
            'U03': { nome: 'Frequência urinária aumentada', componente: 1 },
            'U04': { nome: 'Incontinência urinária', componente: 1 },
            'U05': { nome: 'Retenção urinária', componente: 1 },
            'U06': { nome: 'Hematúria/sangue na urina', componente: 1 },
            'U07': { nome: 'Urina turva/odor forte', componente: 1 },
            'U08': { nome: 'Poliúria', componente: 1 },
            'U09': { nome: 'Nictúria', componente: 1 },
            'U10': { nome: 'Dor lombar renal', componente: 1 },
            'U11': { nome: 'Dor pélvica', componente: 1 },
            'U12': { nome: 'Problema urinário NE', componente: 1 },
            'U13': { nome: 'Alteração da micção', componente: 1 },
            'U14': { nome: 'Medo de doença renal', componente: 1 },
            'U26': { nome: 'Medo de câncer urinário', componente: 1 },
            'U27': { nome: 'Medo de outras doenças urinárias', componente: 1 },
            'U28': { nome: 'Limitação/incapacidade urinária', componente: 1 },
            'U29': { nome: 'Sinais/sintomas urinários NE', componente: 1 },
            'U30': { nome: 'EAS/análise de urina', componente: 2 },
            'U31': { nome: 'Urocultura', componente: 2 },
            'U32': { nome: 'Ultrassom renal', componente: 2 },
            'U33': { nome: 'Urografia', componente: 2 },
            'U34': { nome: 'Cistoscopia', componente: 2 },
            'U35': { nome: 'Teste de função renal', componente: 2 },
            'U50': { nome: 'Antibiótico urinário', componente: 3 },
            'U51': { nome: 'Medicação urinária', componente: 3 },
            'U52': { nome: 'Cateterismo urinário', componente: 3 },
            'U53': { nome: 'Drenagem urinária', componente: 3 },
            'U54': { nome: 'Litotripsia', componente: 3 },
            'U70': { nome: 'Infecção urinária NE', componente: 7 },
            'U71': { nome: 'Cistite', componente: 7 },
            'U72': { nome: 'Uretrite', componente: 7 },
            'U73': { nome: 'Pielonefrite', componente: 7 },
            'U74': { nome: 'Cálculo renal', componente: 7 },
            'U75': { nome: 'Cálculo ureteral', componente: 7 },
            'U76': { nome: 'Cálculo vesical', componente: 7 },
            'U77': { nome: 'Neoplasia maligna renal', componente: 7 },
            'U78': { nome: 'Neoplasia benigna renal', componente: 7 },
            'U79': { nome: 'Neoplasia urinária NE', componente: 7 },
            'U80': { nome: 'Traumatismo renal', componente: 7 },
            'U81': { nome: 'Traumatismo vesical', componente: 7 },
            'U82': { nome: 'Malformação congênita urinária', componente: 7 },
            'U83': { nome: 'Doença renal crônica', componente: 7 },
            'U84': { nome: 'Insuficiência renal aguda', componente: 7 },
            'U85': { nome: 'Hipertensão renovascular', componente: 7 },
            'U86': { nome: 'Síndrome nefrótica', componente: 7 },
            'U87': { nome: 'Glomerulonefrite', componente: 7 },
            'U88': { nome: 'Bexiga neurogênica', componente: 7 },
            'U89': { nome: 'Incontinência urinária', componente: 7 },
            'U90': { nome: 'Retenção urinária', componente: 7 },
            'U91': { nome: 'Hidronefrose', componente: 7 },
            'U92': { nome: 'Doença renal NE', componente: 7 },
            'U93': { nome: 'Distúrbio miccional NE', componente: 7 },
            'U94': { nome: 'Infecção urinária recorrente', componente: 7 },
            'U95': { nome: 'Síndrome da bexiga hiperativa', componente: 7 },
            'U96': { nome: 'Infecção urinária em crianças', componente: 7 },
            'U97': { nome: 'Doença urológica NE', componente: 7 },
            'U98': { nome: 'Hematúria NE', componente: 7 },
            'U99': { nome: 'Outras doenças urinárias', componente: 7 },
        }
    },

    // ===== CAPÍTULO W - GRAVIDEZ E PLANEJAMENTO FAMILIAR =====
    W: {
        nome: 'Gravidez, Parto e Planejamento Familiar',
        descricao: 'Problemas relacionados à gestação, parto e contracepção',
        rubricas: {
            'W01': { nome: 'Suspeita de gravidez', componente: 1 },
            'W02': { nome: 'Amenorreia', componente: 1 },
            'W03': { nome: 'Enjoo matinal', componente: 1 },
            'W04': { nome: 'Sangramento vaginal na gravidez', componente: 1 },
            'W05': { nome: 'Falta de ar na gravidez', componente: 1 },
            'W06': { nome: 'Inchaço na gravidez', componente: 1 },
            'W07': { nome: 'Contrações/parto', componente: 1 },
            'W08': { nome: 'Problema na amamentação', componente: 1 },
            'W09': { nome: 'Preocupação com gravidez', componente: 1 },
            'W10': { nome: 'Contracepção pós-coital', componente: 1 },
            'W11': { nome: 'Contracepção oral', componente: 1 },
            'W12': { nome: 'DIU/contracepção intrauterina', componente: 1 },
            'W13': { nome: 'Contracepção com camisinha', componente: 1 },
            'W14': { nome: 'Contracepção NE', componente: 1 },
            'W15': { nome: 'Problema com contracepção', componente: 1 },
            'W16': { nome: 'Medo de gravidez', componente: 1 },
            'W17': { nome: 'Infertilidade', componente: 1 },
            'W18': { nome: 'Desejo de gravidez', componente: 1 },
            'W19': { nome: 'Problema na gravidez NE', componente: 1 },
            'W20': { nome: 'Sintomas na gravidez', componente: 1 },
            'W21': { nome: 'Sintomas pós-parto', componente: 1 },
            'W22': { nome: 'Sinais/sintomas de aborto', componente: 1 },
            'W23': { nome: 'Medo de complicações na gravidez', componente: 1 },
            'W24': { nome: 'Medo de aborto', componente: 1 },
            'W25': { nome: 'Medo de parto', componente: 1 },
            'W26': { nome: 'Medo de anormalidade fetal', componente: 1 },
            'W27': { nome: 'Limitação na gravidez', componente: 1 },
            'W28': { nome: 'Sinais/sintomas da gravidez NE', componente: 1 },
            'W29': { nome: 'Outros sinais/sintomas na gravidez', componente: 1 },
            'W30': { nome: 'Teste de gravidez', componente: 2 },
            'W31': { nome: 'Ultrassom obstétrico', componente: 2 },
            'W32': { nome: 'Avaliação fetal', componente: 2 },
            'W33': { nome: 'Exame pélvico na gravidez', componente: 2 },
            'W34': { nome: 'Monitoramento fetal', componente: 2 },
            'W35': { nome: 'Exame de pré-natal', componente: 2 },
            'W36': { nome: 'Avaliação pós-parto', componente: 2 },
            'W37': { nome: 'Acompanhamento de gravidez', componente: 2 },
            'W50': { nome: 'Suplemento de ácido fólico', componente: 3 },
            'W51': { nome: 'Suplemento de ferro', componente: 3 },
            'W52': { nome: 'Medicação obstétrica', componente: 3 },
            'W53': { nome: 'Orientações pré-natais', componente: 3 },
            'W54': { nome: 'Contracepção (prescrição)', componente: 3 },
            'W55': { nome: 'Aconselhamento pré-natal', componente: 3 },
            'W56': { nome: 'Preparo para o parto', componente: 3 },
            'W57': { nome: 'Amamentação (orientação)', componente: 3 },
            'W58': { nome: 'Contracepção de emergência', componente: 3 },
            'W59': { nome: 'Acompanhamento pós-parto', componente: 3 },
            'W60': { nome: 'Resultado de pré-natal normal', componente: 4 },
            'W61': { nome: 'Resultado de pré-natal anormal', componente: 4 },
            'W62': { nome: 'Encaminhamento obstétrico', componente: 6 },
            'W63': { nome: 'Encaminhamento para pré-natal', componente: 6 },
            'W64': { nome: 'Acompanhamento da gravidez', componente: 6 },
            'W65': { nome: 'Encaminhamento para contracepção', componente: 6 },
            'W66': { nome: 'Acompanhamento pós-parto', componente: 6 },
            'W70': { nome: 'Gravidez normal', componente: 7 },
            'W71': { nome: 'Gravidez de alto risco', componente: 7 },
            'W72': { nome: 'Gravidez ectópica', componente: 7 },
            'W73': { nome: 'Aborto espontâneo', componente: 7 },
            'W74': { nome: 'Aborto provocado', componente: 7 },
            'W75': { nome: 'Gravidez molar', componente: 7 },
            'W76': { nome: 'Diabetes gestacional', componente: 7 },
            'W77': { nome: 'Hipertensão na gravidez', componente: 7 },
            'W78': { nome: 'Pré-eclâmpsia', componente: 7 },
            'W79': { nome: 'Eclâmpsia', componente: 7 },
            'W80': { nome: 'Parto normal', componente: 7 },
            'W81': { nome: 'Parto cesárea', componente: 7 },
            'W82': { nome: 'Parto instrumentado', componente: 7 },
            'W83': { nome: 'Parto prematuro', componente: 7 },
            'W84': { nome: 'Parto pós-termo', componente: 7 },
            'W85': { nome: 'Complicação do trabalho de parto', componente: 7 },
            'W86': { nome: 'Complicação pós-parto', componente: 7 },
            'W87': { nome: 'Infecção pós-parto', componente: 7 },
            'W88': { nome: 'Síndrome de Hellp', componente: 7 },
            'W89': { nome: 'Descolamento prematuro de placenta', componente: 7 },
            'W90': { nome: 'Placenta prévia', componente: 7 },
            'W91': { nome: 'Doença da placenta/cordão', componente: 7 },
            'W92': { nome: 'Lactação/mastite', componente: 7 },
            'W93': { nome: 'Infertilidade', componente: 7 },
            'W94': { nome: 'Morte fetal', componente: 7 },
            'W95': { nome: 'Abortamento NE', componente: 7 },
            'W96': { nome: 'Gravidez NE', componente: 7 },
            'W97': { nome: 'Contracepção NE', componente: 7 },
            'W98': { nome: 'Pré-natal NE', componente: 7 },
            'W99': { nome: 'Outros problemas obstétricos', componente: 7 },
        }
    },

    // ===== CAPÍTULO X - APARELHO GENITAL FEMININO =====
    X: {
        nome: 'Aparelho Genital Feminino (incluindo mama)',
        descricao: 'Problemas ginecológicos e da mama feminina',
        rubricas: {
            'X01': { nome: 'Sangramento vaginal anormal', componente: 1 },
            'X02': { nome: 'Dor pélvica', componente: 1 },
            'X03': { nome: 'Corrimento vaginal', componente: 1 },
            'X04': { nome: 'Prurido vaginal', componente: 1 },
            'X05': { nome: 'Amenorreia', componente: 1 },
            'X06': { nome: 'Dismenorreia', componente: 1 },
            'X07': { nome: 'Menorragia/sangramento excessivo', componente: 1 },
            'X08': { nome: 'Metrorragia', componente: 1 },
            'X09': { nome: 'Alteração menstrual NE', componente: 1 },
            'X10': { nome: 'Dor mamária', componente: 1 },
            'X11': { nome: 'Nódulo mamário', componente: 1 },
            'X12': { nome: 'Secreção mamilar', componente: 1 },
            'X13': { nome: 'Alteração da mama NE', componente: 1 },
            'X14': { nome: 'Sintomas da mama NE', componente: 1 },
            'X15': { nome: 'Dor vulvar', componente: 1 },
            'X16': { nome: 'Dor perineal', componente: 1 },
            'X17': { nome: 'Alteração da vulva', componente: 1 },
            'X18': { nome: 'Sinais/sintomas da vulva NE', componente: 1 },
            'X19': { nome: 'Sintomas ginecológicos NE', componente: 1 },
            'X20': { nome: 'Sintomas de menopausa', componente: 1 },
            'X21': { nome: 'Sintomas pré-menstruais', componente: 1 },
            'X22': { nome: 'Incontinência urinária de esforço', componente: 1 },
            'X23': { nome: 'Prolapso genital', componente: 1 },
            'X24': { nome: 'Dor durante relação sexual', componente: 1 },
            'X25': { nome: 'Sangramento pós-coito', componente: 1 },
            'X26': { nome: 'Medo de câncer ginecológico', componente: 1 },
            'X27': { nome: 'Medo de câncer de mama', componente: 1 },
            'X28': { nome: 'Medo de outras doenças ginecológicas', componente: 1 },
            'X29': { nome: 'Sinais/sintomas ginecológicos NE', componente: 1 },
            'X30': { nome: 'Papanicolau', componente: 2 },
            'X31': { nome: 'Mamografia', componente: 2 },
            'X32': { nome: 'Ultrassom ginecológico', componente: 2 },
            'X33': { nome: 'Colposcopia', componente: 2 },
            'X34': { nome: 'Biopsia de mama', componente: 2 },
            'X35': { nome: 'Exame ginecológico', componente: 2 },
            'X36': { nome: 'Densitometria óssea', componente: 2 },
            'X37': { nome: 'Exame de mama', componente: 2 },
            'X38': { nome: 'Exame de Papanicolau', componente: 2 },
            'X39': { nome: 'Exame ginecológico NE', componente: 2 },
            'X50': { nome: 'Medicação ginecológica', componente: 3 },
            'X51': { nome: 'TRH/terapia de reposição hormonal', componente: 3 },
            'X52': { nome: 'Contracepção hormonal', componente: 3 },
            'X53': { nome: 'Anticoncepcional oral', componente: 3 },
            'X54': { nome: 'DIU', componente: 3 },
            'X55': { nome: 'Antifúngico ginecológico', componente: 3 },
            'X56': { nome: 'Antibiótico ginecológico', componente: 3 },
            'X57': { nome: 'Cirurgia ginecológica', componente: 3 },
            'X58': { nome: 'Cirurgia de mama', componente: 3 },
            'X59': { nome: 'Procedimento ginecológico', componente: 3 },
            'X60': { nome: 'Resultado de Papanicolau normal', componente: 4 },
            'X61': { nome: 'Resultado de Papanicolau anormal', componente: 4 },
            'X62': { nome: 'Encaminhamento ginecológico', componente: 6 },
            'X63': { nome: 'Encaminhamento mastológico', componente: 6 },
            'X64': { nome: 'Acompanhamento ginecológico', componente: 6 },
            'X70': { nome: 'Infecção vaginal', componente: 7 },
            'X71': { nome: 'Candidíase vaginal', componente: 7 },
            'X72': { nome: 'Vaginose bacteriana', componente: 7 },
            'X73': { nome: 'Tricomoníase', componente: 7 },
            'X74': { nome: 'Doença inflamatória pélvica', componente: 7 },
            'X75': { nome: 'Cisto de ovário', componente: 7 },
            'X76': { nome: 'Mioma uterino', componente: 7 },
            'X77': { nome: 'Neoplasia benigna da mama', componente: 7 },
            'X78': { nome: 'Neoplasia maligna da mama', componente: 7 },
            'X79': { nome: 'Neoplasia maligna do colo do útero', componente: 7 },
            'X80': { nome: 'Neoplasia maligna do endométrio', componente: 7 },
            'X81': { nome: 'Neoplasia maligna do ovário', componente: 7 },
            'X82': { nome: 'Neoplasia ginecológica NE', componente: 7 },
            'X83': { nome: 'Endometriose', componente: 7 },
            'X84': { nome: 'Síndrome dos ovários policísticos', componente: 7 },
            'X85': { nome: 'Dismenorreia', componente: 7 },
            'X86': { nome: 'Menopausa', componente: 7 },
            'X87': { nome: 'Síndrome pré-menstrual', componente: 7 },
            'X88': { nome: 'Prolapso uterino', componente: 7 },
            'X89': { nome: 'Doença da mama benigna', componente: 7 },
            'X90': { nome: 'Fibroadenoma de mama', componente: 7 },
            'X91': { nome: 'Mastite', componente: 7 },
            'X92': { nome: 'Doença da vulva/vagina', componente: 7 },
            'X93': { nome: 'Incontinência urinária de esforço', componente: 7 },
            'X94': { nome: 'Atrofia vaginal', componente: 7 },
            'X95': { nome: 'Displasia cervical', componente: 7 },
            'X96': { nome: 'Disfunção sexual feminina', componente: 7 },
            'X97': { nome: 'Doença do colo uterino', componente: 7 },
            'X98': { nome: 'Doença do útero', componente: 7 },
            'X99': { nome: 'Outras doenças ginecológicas', componente: 7 },
        }
    },

    // ===== CAPÍTULO Y - APARELHO GENITAL MASCULINO =====
    Y: {
        nome: 'Aparelho Genital Masculino',
        descricao: 'Problemas urológicos e genitais masculinos',
        rubricas: {
            'Y01': { nome: 'Dor testicular', componente: 1 },
            'Y02': { nome: 'Dor peniana', componente: 1 },
            'Y03': { nome: 'Secreção uretral', componente: 1 },
            'Y04': { nome: 'Alteração urinária', componente: 1 },
            'Y05': { nome: 'Disfunção erétil', componente: 1 },
            'Y06': { nome: 'Alteração da ejaculação', componente: 1 },
            'Y07': { nome: 'Diminuição do desejo sexual', componente: 1 },
            'Y08': { nome: 'Nódulo testicular', componente: 1 },
            'Y09': { nome: 'Inchaço testicular', componente: 1 },
            'Y10': { nome: 'Problema na uretra', componente: 1 },
            'Y11': { nome: 'Problema na próstata', componente: 1 },
            'Y12': { nome: 'Dor pélvica masculina', componente: 1 },
            'Y13': { nome: 'Alteração miccional NE', componente: 1 },
            'Y14': { nome: 'Medo de câncer de próstata', componente: 1 },
            'Y15': { nome: 'Medo de câncer testicular', componente: 1 },
            'Y16': { nome: 'Medo de outras doenças genitais', componente: 1 },
            'Y17': { nome: 'Limitação/incapacidade genital', componente: 1 },
            'Y18': { nome: 'Sinais/sintomas genitais NE', componente: 1 },
            'Y19': { nome: 'Sinais/sintomas genitais NE', componente: 1 },
            'Y30': { nome: 'Exame geniturinário', componente: 2 },
            'Y31': { nome: 'Ultrassom de próstata', componente: 2 },
            'Y32': { nome: 'Ultrassom testicular', componente: 2 },
            'Y33': { nome: 'PSA/exame de sangue', componente: 2 },
            'Y34': { nome: 'Urofluxometria', componente: 2 },
            'Y35': { nome: 'Toque retal', componente: 2 },
            'Y36': { nome: 'Exame de urina', componente: 2 },
            'Y37': { nome: 'Cistoscopia', componente: 2 },
            'Y50': { nome: 'Medicação urológica', componente: 3 },
            'Y51': { nome: 'Inibidor de 5-alfa-redutase', componente: 3 },
            'Y52': { nome: 'Alfa-bloqueador', componente: 3 },
            'Y53': { nome: 'Medicamento para disfunção erétil', componente: 3 },
            'Y54': { nome: 'Antibiótico urológico', componente: 3 },
            'Y55': { nome: 'Cirurgia urológica', componente: 3 },
            'Y56': { nome: 'Procedimento urológico', componente: 3 },
            'Y57': { nome: 'Cateterismo', componente: 3 },
            'Y58': { nome: 'Cirurgia de próstata', componente: 3 },
            'Y59': { nome: 'Procedimento genital masculino', componente: 3 },
            'Y62': { nome: 'Encaminhamento urológico', componente: 6 },
            'Y63': { nome: 'Acompanhamento urológico', componente: 6 },
            'Y70': { nome: 'Infecção genital masculina', componente: 7 },
            'Y71': { nome: 'Uretrite', componente: 7 },
            'Y72': { nome: 'Prostatite', componente: 7 },
            'Y73': { nome: 'Epididimite/orquite', componente: 7 },
            'Y74': { nome: 'Doença sexualmente transmissível', componente: 7 },
            'Y75': { nome: 'Neoplasia benigna da próstata', componente: 7 },
            'Y76': { nome: 'Neoplasia maligna da próstata', componente: 7 },
            'Y77': { nome: 'Neoplasia testicular', componente: 7 },
            'Y78': { nome: 'Neoplasia peniana', componente: 7 },
            'Y79': { nome: 'Neoplasia genital NE', componente: 7 },
            'Y80': { nome: 'Traumatismo genital', componente: 7 },
            'Y81': { nome: 'Malformação congênita genital', componente: 7 },
            'Y82': { nome: 'Disfunção erétil', componente: 7 },
            'Y83': { nome: 'Ejaculação precoce', componente: 7 },
            'Y84': { nome: 'Esterilidade masculina', componente: 7 },
            'Y85': { nome: 'Hiperplasia prostática benigna', componente: 7 },
            'Y86': { nome: 'Doença da próstata NE', componente: 7 },
            'Y87': { nome: 'Fimose', componente: 7 },
            'Y88': { nome: 'Criptorquidia', componente: 7 },
            'Y89': { nome: 'Hipogonadismo', componente: 7 },
            'Y90': { nome: 'Disfunção sexual masculina', componente: 7 },
            'Y91': { nome: 'Doença do pênis', componente: 7 },
            'Y92': { nome: 'Doença da uretra', componente: 7 },
            'Y93': { nome: 'Distúrbio da ejaculação', componente: 7 },
            'Y94': { nome: 'Transtorno sexual masculino', componente: 7 },
            'Y95': { nome: 'Doença testicular', componente: 7 },
            'Y96': { nome: 'Doença genital NE', componente: 7 },
            'Y97': { nome: 'Problema urológico NE', componente: 7 },
            'Y98': { nome: 'Distúrbio genital NE', componente: 7 },
            'Y99': { nome: 'Outras doenças genitais masculinas', componente: 7 },
        }
    },

    // ===== CAPÍTULO Z - PROBLEMAS SOCIAIS =====
    Z: {
        nome: 'Problemas Sociais',
        descricao: 'Problemas psicossociais e questões sociais',
        rubricas: {
            'Z01': { nome: 'Problema de renda/recursos', componente: 1 },
            'Z02': { nome: 'Problema de habitação', componente: 1 },
            'Z03': { nome: 'Problema de alimentação', componente: 1 },
            'Z04': { nome: 'Problema de desemprego', componente: 1 },
            'Z05': { nome: 'Problema de aposentadoria', componente: 1 },
            'Z06': { nome: 'Problema de educação', componente: 1 },
            'Z07': { nome: 'Problema de transporte', componente: 1 },
            'Z08': { nome: 'Problema de violência', componente: 1 },
            'Z09': { nome: 'Problema de abuso', componente: 1 },
            'Z10': { nome: 'Problema de negligência', componente: 1 },
            'Z11': { nome: 'Problema de relacionamento', componente: 1 },
            'Z12': { nome: 'Problema familiar', componente: 1 },
            'Z13': { nome: 'Problema parental', componente: 1 },
            'Z14': { nome: 'Problema de luto', componente: 1 },
            'Z15': { nome: 'Problema de isolamento social', componente: 1 },
            'Z16': { nome: 'Problema de trabalho', componente: 1 },
            'Z17': { nome: 'Problema de estresse', componente: 1 },
            'Z18': { nome: 'Problema de adaptação', componente: 1 },
            'Z19': { nome: 'Problema social NE', componente: 1 },
            'Z20': { nome: 'Medo/ansiedade social', componente: 1 },
            'Z21': { nome: 'Discriminação/preconceito', componente: 1 },
            'Z22': { nome: 'Problema de acesso à saúde', componente: 1 },
            'Z23': { nome: 'Problema de seguridade social', componente: 1 },
            'Z24': { nome: 'Problema de legalidade', componente: 1 },
            'Z25': { nome: 'Problema de migração', componente: 1 },
            'Z26': { nome: 'Problema de refugiado', componente: 1 },
            'Z27': { nome: 'Problema de comunidade', componente: 1 },
            'Z28': { nome: 'Limitação social NE', componente: 1 },
            'Z29': { nome: 'Sinais/sintomas sociais NE', componente: 1 },
            'Z30': { nome: 'Avaliação social', componente: 2 },
            'Z31': { nome: 'Entrevista social', componente: 2 },
            'Z32': { nome: 'Avaliação de risco social', componente: 2 },
            'Z33': { nome: 'Avaliação familiar', componente: 2 },
            'Z34': { nome: 'Avaliação de suporte social', componente: 2 },
            'Z50': { nome: 'Aconselhamento social', componente: 3 },
            'Z51': { nome: 'Orientação social', componente: 3 },
            'Z52': { nome: 'Encaminhamento social', componente: 3 },
            'Z53': { nome: 'Visita domiciliar', componente: 3 },
            'Z54': { nome: 'Suporte social', componente: 3 },
            'Z55': { nome: 'Intervenção familiar', componente: 3 },
            'Z56': { nome: 'Mediação social', componente: 3 },
            'Z57': { nome: 'Terapia familiar', componente: 3 },
            'Z58': { nome: 'Acompanhamento social', componente: 3 },
            'Z59': { nome: 'Procedimento social', componente: 3 },
            'Z60': { nome: 'Avaliação social concluída', componente: 4 },
            'Z61': { nome: 'Avaliação social pendente', componente: 4 },
            'Z62': { nome: 'Encaminhamento para serviço social', componente: 6 },
            'Z63': { nome: 'Encaminhamento para psicologia', componente: 6 },
            'Z64': { nome: 'Encaminhamento para assistência social', componente: 6 },
            'Z65': { nome: 'Encaminhamento para judicial', componente: 6 },
            'Z66': { nome: 'Acompanhamento social', componente: 6 },
            'Z70': { nome: 'Problema de pobreza', componente: 7 },
            'Z71': { nome: 'Problema de vulnerabilidade', componente: 7 },
            'Z72': { nome: 'Problema de exclusão social', componente: 7 },
            'Z73': { nome: 'Problema de violência doméstica', componente: 7 },
            'Z74': { nome: 'Problema de abuso infantil', componente: 7 },
            'Z75': { nome: 'Problema de negligência', componente: 7 },
            'Z76': { nome: 'Problema de abuso de substâncias', componente: 7 },
            'Z77': { nome: 'Problema de encarceramento', componente: 7 },
            'Z78': { nome: 'Problema de refugiado', componente: 7 },
            'Z79': { nome: 'Problema de migração', componente: 7 },
            'Z80': { nome: 'Problema de luto', componente: 7 },
            'Z81': { nome: 'Problema de divórcio/separação', componente: 7 },
            'Z82': { nome: 'Problema de guarda de filhos', componente: 7 },
            'Z83': { nome: 'Problema de adoção', componente: 7 },
            'Z84': { nome: 'Problema de abandono', componente: 7 },
            'Z85': { nome: 'Problema de conflito familiar', componente: 7 },
            'Z86': { nome: 'Problema de bullying', componente: 7 },
            'Z87': { nome: 'Problema de assédio', componente: 7 },
            'Z88': { nome: 'Problema de preconceito/discriminação', componente: 7 },
            'Z89': { nome: 'Problema de desemprego de longa duração', componente: 7 },
            'Z90': { nome: 'Problema de falta de moradia', componente: 7 },
            'Z91': { nome: 'Problema de saneamento', componente: 7 },
            'Z92': { nome: 'Problema de acesso à saúde', componente: 7 },
            'Z93': { nome: 'Problema de seguridade social', componente: 7 },
            'Z94': { nome: 'Problema de trabalho infantil', componente: 7 },
            'Z95': { nome: 'Problema de exploração', componente: 7 },
            'Z96': { nome: 'Problema de tráfico humano', componente: 7 },
            'Z97': { nome: 'Problema de comunidade NE', componente: 7 },
            'Z98': { nome: 'Problema social NE', componente: 7 },
            'Z99': { nome: 'Outros problemas sociais', componente: 7 },
        }
    }
};

// ===== FUNÇÕES DE ACESSO =====

// Obter dados de um capítulo específico
function getCapituloData(codigo) {
    return CIAP2_DADOS[codigo] || null;
}

// Obter todos os capítulos
function getAllCapitulos() {
    return CIAP2_DADOS;
}

// Buscar rubricas por termo
function buscarNaCIAP2(termo) {
    const resultados = [];
    const termoLower = termo.toLowerCase();

    for (const [capCodigo, capDados] of Object.entries(CIAP2_DADOS)) {
        for (const [codigo, rubrica] of Object.entries(capDados.rubricas)) {
            if (codigo.toLowerCase().includes(termoLower) ||
                rubrica.nome.toLowerCase().includes(termoLower)) {
                resultados.push({
                    codigo: codigo,
                    nome: rubrica.nome,
                    componente: rubrica.componente,
                    capitulo: capCodigo,
                    capituloNome: capDados.nome
                });
            }
        }
    }

    return resultados;
}

// Contar rubricas
function contarRubricas() {
    let total = 0;
    for (const [capCodigo, capDados] of Object.entries(CIAP2_DADOS)) {
        total += Object.keys(capDados.rubricas).length;
    }
    return total;
}

// Obter rubricas por componente
function getRubricasPorComponente(capitulo, componente) {
    const cap = CIAP2_DADOS[capitulo];
    if (!cap) return {};
    const result = {};
    for (const [codigo, rubrica] of Object.entries(cap.rubricas)) {
        if (rubrica.componente === componente) {
            result[codigo] = rubrica;
        }
    }
    return result;
}